# Generated by Django 4.2.17 on 2025-01-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gadgets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Available', 'Active'), ('Unavailable', 'Inactive'), ('Destroyed', 'Destroyed'), ('Decommissioned', 'Decommissioned')])),
            ],
        ),
    ]
